# Base directory to start looking for files (relative or absolute).
base_dir: 'qa_generation_input'

# Directory where the QA outputs and debug files will be saved.
output_dir: 'qa_generation_output'

header_prompt: |
  Analyze the file contents below and generate a detailed, diverse, and well-structured Question & Answer list.

# Footer prompt: Output expectations.
footer_prompt: |
  --- Output ---

  Q:
  A:

  Q:
  A:

  Q:
  A:

  continue...

# Define the file groups with their associated files, iterations, and each group's prompt.
file_groups:
  UninstallModel:
    iterations: 20
    files: ['UninstallModelDoc.txt']
    group_prompt: |
      {files_content}
  DeleteModel:
    iterations: 20
    files: ['DeleteModelDoc.txt']
    group_prompt: |
      {files_content}
  ListModels:
    iterations: 20
    files: ['ListModelsDoc.txt']
    group_prompt: |
      {files_content}
  Connect:
    iterations: 20
    files: ['ConnectDoc.txt']
    group_prompt: |
      {files_content}
  CopyTrainingData:
    iterations: 20
    files: ['CopyTrainingDataDoc.txt']
    group_prompt: |
      {files_content}
  CreateAndRunContainer:
    iterations: 20
    files: ['CreateAndRunContainerDoc.txt']
    group_prompt: |
      {files_content}
  Build:
    iterations: 60
    files: ['BuildDoc.txt']
    group_prompt: |
      {files_content}
  TrainModelUnsloth:
    iterations: 40
    files: [TrainModelUnsloth.txt]
    group_prompt: |
      {files_content}
  TrainModelTorchtune:
    iterations: 40
    files: [TrainModelTorchtune.txt1]
    group_prompt: |
      {files_content}
  InstallModel:
    iterations: 20
    files: [InstallModelDoc.txt]
    group_prompt: |
      {files_content}
  ReadMe:
    iterations: 60
    files: [ReadMeDoc.txt]
    group_prompt: |
      {files_content}
  FineTuningGuide:
    iterations: 40
    files: [FineTuningGuideDoc.txt]
    group_prompt: |
      {files_content}
  Supervisord:
    iterations: 20
    files: [supervisord.conf]
    group_prompt: |
      {files_content}
  CopyConfigs:
    iterations: 20
    files: [CopyConfigDoc.txt]
    group_prompt: |
      {files_content}
  ConvertJSONLtoJSON:
    iterations: 20
    files: [ConvertJSONLtoJSONDoc.txt]
    group_prompt: |
      {files_content}
