global:
  base_dir: qa_generation_input
  output_dir: qa_generation_output
  output_base_path: /var/kolo_data
  ollama_url: http://localhost:11434/api/generate

providers:
  answer:
    provider: ollama # Use "ollama" or "openai"
    model: KoloLLM8B-Round3

AnswerInstructionList:
  - name: 'Default'
    instruction:
      - ''

FileHeaders:
  - name: 'DefaultFileHeader'
    description: 'The file contents for: {file_name}'

AnswerPrompt:
  - name: 'DefaultAnswerPrompt'
    description: |
      {file_content}
      {instruction}
      {question}

file_groups:
  UninstallModel:
    iterations: 3
    files:
      - uninstall_model.ps1
    file_header: DefaultFileHeader
    answer_prompt: DefaultAnswerPrompt
    answer_instruction_list: [Default]
    question_list:
      - 'What does the uninstall model script do exactly?'
      - 'How do I use the uninstall_model.ps1 script?'
      - 'Which service does uninstall model script use?'
  # README:
  #   iterations: 5
  #   files:
  #     - README.md
  #   question_prompt: NoFileName
  #   generate_question_list: [DocumentList]
  #   question_instruction_list: [CasualandFormal]
  #   file_header: DefaultFileHeader
  #   answer_prompt: DefaultAnswerPrompt
  #   answer_instruction_list: [Default]
  # DeleteModel:
  #   iterations: 3
  #   files:
  #     - delete_model.ps1
  #   question_prompt: WithFileName
  #   generate_question_list: [CodingList]
  #   question_instruction_list: [CasualandFormal]
  #   file_header: DefaultFileHeader
  #   answer_prompt: DefaultAnswerPrompt
  #   answer_instruction_list: [Default]
  # BuildImage:
  #   iterations: 3
  #   question_prompt: WithFileName
  #   generate_question_list: [CodingList, DocumentList]
  #   question_instruction_list: [CasualandFormal]
  #   file_header: DefaultFileHeader
  #   answer_prompt: DefaultAnswerPrompt
  #   answer_instruction_list: [Default]
  #   files:
  #     - build_image.ps1
  #     - dockerfile
  #     - supervisord.conf
  # TrainTorchTune:
  #   iterations: 3
  #   question_prompt: WithFileName
  #   generate_question_list: [CodingList]
  #   question_instruction_list: [CasualandFormal]
  #   file_header: DefaultFileHeader
  #   answer_prompt: DefaultAnswerPrompt
  #   answer_instruction_list: [Default]
  #   files:
  #     - train_model_torchtune.ps1
  #     - merge_lora.py
  #     - convert_jsonl_to_json.py
  # TrainUnsloth:
  #   iterations: 3
  #   question_prompt: WithFileName
  #   generate_question_list: [CodingList]
  #   question_instruction_list: [CasualandFormal]
  #   file_header: DefaultFileHeader
  #   answer_prompt: DefaultAnswerPrompt
  #   answer_instruction_list: [Default]
  #   files:
  #     - train_model_unsloth.ps1
  #     - train.py
  # InstallModel:
  #   iterations: 3
  #   question_prompt: WithFileName
  #   generate_question_list: [CodingList]
  #   question_instruction_list: [CasualandFormal]
  #   file_header: DefaultFileHeader
  #   answer_prompt: DefaultAnswerPrompt
  #   answer_instruction_list: [Default]
  #   files:
  #     - install_model.ps1
  # ListModels:
  #   iterations: 3
  #   question_prompt: WithFileName
  #   generate_question_list: [CodingList]
  #   question_instruction_list: [CasualandFormal]
  #   file_header: DefaultFileHeader
  #   answer_prompt: DefaultAnswerPrompt
  #   answer_instruction_list: [Default]
  #   files:
  #     - list_models.ps1
  # FineTuningGuide:
  #   iterations: 5
  #   question_prompt: NoFileName
  #   generate_question_list: [DocumentList]
  #   question_instruction_list: [CasualandFormal]
  #   file_header: DefaultFileHeader
  #   answer_prompt: DefaultAnswerPrompt
  #   answer_instruction_list: [Default]
  #   files:
  #     - FineTuningGuide.md
  # GenerateTrainingDataGuide:
  #   iterations: 5
  #   question_prompt: NoFileName
  #   generate_question_list: [DocumentList]
  #   question_instruction_list: [CasualandFormal]
  #   file_header: DefaultFileHeader
  #   answer_prompt: DefaultAnswerPrompt
  #   answer_instruction_list: [Default]
  #   files:
  #     - GenerateTrainingDataGuide.md
