global:
  base_dir: qa_generation_input
  output_dir: qa_generation_output
  output_base_path: /var/kolo_data
  ollama_url: http://localhost:11434/api/generate

providers:
  question:
    provider: openai # Use "ollama" or "openai"
    model: gpt-4o-mini
  answer:
    provider: openai # Use "ollama" or "openai"
    model: gpt-4o-mini

prompts:
  question_prompt_header: >
    Create a list of questions that thoroughly explore the functionality and workings of the following.
  question_prompt_footer: |
    Please generate the following list:
    1. <question 1>
    2. <question 2>
    3. <question 3>
    etc.
  individual_question_prompt: 'File contents for : "{file_name}"'
  group_question_prompt: '{files_content}'
  answer_prompt: |
    {answer}

    Show the relevant content before answering the question.

file_groups:
  TrainTorchTune:
    iterations: 50
    files:
      - train_model_torchtune.ps1
      - merge_lora.py
      - convert_jsonl_to_json.py
  BuildImage:
    iterations: 50
    files:
      - build_image.ps1
      - dockerfile
      - supervisord.conf
  UninstallModel:
    iterations: 15
    files:
      - uninstall_model.ps1
  DeleteModel:
    iterations: 15
    files:
      - delete_model.ps1
  RunContainer:
    iterations: 15
    files:
      - create_and_run_container.ps1
      - run_container.ps1
  TrainUnsloth:
    iterations: 50
    files:
      - train_model_unsloth.ps1
      - train.py
  TrainingPSCommands:
    iterations: 50
    files:
      - train_model_torchtune.ps1
      - train_model_unsloth.ps1
  InstallModel:
    iterations: 15
    files:
      - install_model.ps1
  ListModels:
    iterations: 15
    files:
      - list_models.ps1
  CopyScripts:
    iterations: 15
    files:
      - copy_scripts.ps1
  CopyConfigs:
    iterations: 15
    files:
      - copy_configs.ps1
  ConnectSSH:
    iterations: 15
    files:
      - connect.ps1
  FineTuningGuide:
    iterations: 50
    files:
      - FineTuningGuide.md
  README:
    iterations: 50
    files:
      - README.md
  GenerateQAData:
    iterations: 50
    files:
      - generate_qa_data.ps1
      - generate_qa_data.py
      - generate_qa_config.yaml
  ConvertQAData:
    iterations: 25
    files:
      - parse_qa_data.py
      - convert_qa_output.ps1
  GenerateTrainingDataGuide:
    iterations: 50
    files:
      - GenerateTrainingDataGuide.md
  CopyQAInputGeneration:
    iterations: 15
    files:
      - copy_qa_input_generation.ps1
  GenerateQADataPy:
    iterations: 50
    files:
      - generate_qa_data.py
  GenerateQADataPs1:
    iterations: 15
    files:
      - generate_qa_data.ps1
  GenerateQADataYaml:
    iterations: 15
    files:
      - generate_qa_config.yaml
