# config.yaml

# Base directory to start looking for files (relative or absolute).
base_dir: 'qa_generation_input'

# Directory where the QA outputs and debug files will be saved.
output_dir: 'qa_generation_output'

# The QA prompt template. The placeholder {files_content} will be replaced with the combined file content.
qa_prompt_template: |
  Generate a comprehensive FAQ based on the provided file contents. Every question must explicitly reference the relevant file name(s) mentioned in the "Files Content" section. The answers should be detailed and provide as much context as possible.

  --- Files Content ---

  {files_content}

  ---

  --- Output ---

  Q:
  A:

  Q:
  A:

  Q:
  A:

  ... (continue as needed)

# Define the file groups, their associated files, and how many times each group should be processed.
file_groups:
  UninstallModel:
    iterations: 8
    files: ['uninstall_model.ps1']
  BuildImage:
    iterations: 64
    files: ['build_image.ps1', 'dockerfile', 'supervisord.conf']
  RunContainer:
    iterations: 8
    files: ['create_and_run_container.ps1', 'run_container.ps1']
  TrainUnsloth:
    iterations: 32
    files: ['train_model_unsloth.ps1', 'train.py']
  TrainTorchTune:
    iterations: 32
    files:
      ['train_model_torchtune.ps1', 'merge_lora.py', 'convert_jsonl_to_json.py']
  TrainingPSCommands:
    iterations: 32
    files: ['train_model_torchtune.ps1', 'train_model_unsloth.ps1']
  InstallModel:
    iterations: 8
    files: ['install_model.ps1']
  ListModels:
    iterations: 8
    files: ['list_models.ps1']
  DeleteModel:
    iterations: 8
    files: ['delete_model.ps1']
  CopyScripts:
    iterations: 8
    files: ['copy_scripts.ps1']
  CopyConfigs:
    iterations: 8
    files: ['copy_configs.ps1']
  ConnectSSH:
    iterations: 8
    files: ['connect.ps1']
  FineTuningGuide:
    iterations: 64
    files: ['FineTuningGuide.md']
  README:
    iterations: 128
    files: ['README.md']
  ModelPSCommands:
    iterations: 16
    files:
      [
        'install_model.ps1',
        'uninstall_model.ps1',
        'list_models.ps1',
        'delete_model.ps1',
      ]
