global:
  base_dir: 'qa_generation_input'
  output_dir: 'qa_generation_output'
  output_base_path: '/var/kolo_data'

  # Provider settings: choose "openai" or "ollama"
  provider: 'ollama'
  openai:
    question_model: 'gpt-4o-mini'
    answer_model: 'gpt-4o-mini'
  ollama:
    url: 'http://localhost:11434/api/generate'
    question_model: 'llama3.1'
    answer_model: 'llama3.1'

prompts:
  header: |
    Generate a list of questions that will cover the full contents of the file.
  footer: |
    --- Output ---

    1.

    2.

    3.
    ... (continue as needed)
  default_individual: 'Each question must include "{file_name}"'
  default_group: '{files_content}'
  default_answer: 'Based on the file content provided, answer the following question in detail.'

file_groups:
  BuildImage:
    iterations: 15
    files:
      - build_image.ps1
      - dockerfile
      - supervisord.conf
    prompts:
      group: |
        {files_content}
      individual: |
        Each question must include "{file_name}"
  UninstallModel:
    iterations: 5
    files:
      - uninstall_model.ps1
    prompts:
      group: |
        {files_content}
      individual: |
        Each question must include "{file_name}"
  DeleteModel:
    iterations: 5
    files:
      - delete_model.ps1
    prompts:
      group: |
        {files_content}
      individual: |
        Each question must include "{file_name}"
  RunContainer:
    iterations: 5
    files:
      - create_and_run_container.ps1
      - run_container.ps1
    prompts:
      group: |
        {files_content}
      individual: |
        Each question must include "{file_name}"
  TrainUnsloth:
    iterations: 15
    files:
      - train_model_unsloth.ps1
      - train.py
    prompts:
      group: |
        {files_content}
      individual: |
        Each question must include "{file_name}"
  TrainTorchTune:
    iterations: 15
    files:
      - train_model_torchtune.ps1
      - merge_lora.py
      - convert_jsonl_to_json.py
    prompts:
      group: |
        {files_content}
      individual: |
        Each question must include "{file_name}"
  TrainingPSCommands:
    iterations: 15
    files:
      - train_model_torchtune.ps1
      - train_model_unsloth.ps1
    prompts:
      group: |
        {files_content}
      individual: |
        Each question must include "{file_name}"
  InstallModel:
    iterations: 5
    files:
      - install_model.ps1
    prompts:
      group: |
        {files_content}
      individual: |
        Each question must include "{file_name}"
  ListModels:
    iterations: 5
    files:
      - list_models.ps1
    prompts:
      group: |
        {files_content}
      individual: |
        Each question must include "{file_name}"
  CopyScripts:
    iterations: 5
    files:
      - copy_scripts.ps1
    prompts:
      group: |
        {files_content}
      individual: |
        Each question must include "{file_name}"
  CopyConfigs:
    iterations: 5
    files:
      - copy_configs.ps1
    prompts:
      group: |
        {files_content}
      individual: |
        Each question must include "{file_name}"
  ConnectSSH:
    iterations: 5
    files:
      - connect.ps1
    prompts:
      group: |
        {files_content}
      individual: |
        Each question must include "{file_name}"
  FineTuningGuide:
    iterations: 15
    files:
      - FineTuningGuide.md
    prompts:
      group: |
        {files_content}
  README:
    iterations: 15
    files:
      - README.md
    prompts:
      group: |
        {files_content}
