global:
  base_dir: qa_generation_input
  output_dir: qa_generation_output
  output_base_path: /var/kolo_data
  ollama_url: http://localhost:11434/api/generate

providers:
  question:
    provider: openai # Use "ollama" or "openai"
    model: gpt-4o-mini
  answer:
    provider: openai # Use "ollama" or "openai"
    model: gpt-4o-mini

AnswerInstructionList:
  - name: 'Default'
    instruction:
      - ''

QuestionInstructionList:
  - name: 'ToneInstructions'
    instruction:
      - 'Keep it short.'
      - ''
      - 'Use slang.'
      - 'Use broken english.'
      - 'Sound like a developer.'

GenerateQuestionLists:
  - name: 'DocumentList'
    questions:
      - 'Write a question as if you are an experienced user with made up specific requirements and details and you want the LLM to work for you using the following information.'
      - 'Write a question as if you are a new user and you want to know how to do something from the following information.'
      - 'Write a question as if you are a new user and you want to know something specific from the following information.'
      - 'Write a question as if you are a new user and you want to have a broad understanding of the following information.'
      - 'Write a question as if you are a new user that is confused and wants something rephrased from the following information.'

  - name: 'CodingList'
    questions:
      - 'Write a question as if you are an experienced user that wants to know a specific implementation detail in the following code.'
      - 'Write a question as if you are a new user that wants to know how to use the following code for a particular situation.'

FileHeaders:
  - name: 'DefaultFileHeader'
    description: 'The file contents for: {file_name}'

AnswerPrompt:
  - name: 'DefaultAnswerPrompt'
    description: |
      {question}
      {instruction}
      ---
      {file_content}

QuestionPrompt:
  - name: 'NoFileName'
    description: |
      {generate_question}
      {instruction}
      ---
      {file_content}
  - name: 'WithFileName'
    description: |
      {generate_question}
      {instruction}
      You are required to reference {file_name_list} in the question that you create!
      ---
      {file_content}

file_groups:
  UninstallModel:
    iterations: 10
    files:
      - uninstall_model.ps1
    question_prompt: WithFileName
    generate_question_list: [CodingList]
    question_instruction_list: [ToneInstructions]
    file_header: DefaultFileHeader
    answer_prompt: DefaultAnswerPrompt
    answer_instruction_list: [Default]
  README:
    iterations: 30
    files:
      - README.md
    question_prompt: NoFileName
    generate_question_list: [DocumentList]
    question_instruction_list: [ToneInstructions]
    file_header: DefaultFileHeader
    answer_prompt: DefaultAnswerPrompt
    answer_instruction_list: [Default]
  DeleteModel:
    iterations: 10
    files:
      - delete_model.ps1
    question_prompt: WithFileName
    generate_question_list: [CodingList]
    question_instruction_list: [ToneInstructions]
    file_header: DefaultFileHeader
    answer_prompt: DefaultAnswerPrompt
    answer_instruction_list: [Default]
  BuildImage:
    iterations: 10
    question_prompt: WithFileName
    generate_question_list: [CodingList, DocumentList]
    question_instruction_list: [ToneInstructions]
    file_header: DefaultFileHeader
    answer_prompt: DefaultAnswerPrompt
    answer_instruction_list: [Default]
    files:
      - build_image.ps1
      - dockerfile
      - supervisord.conf
  TrainTorchTune:
    iterations: 10
    question_prompt: WithFileName
    generate_question_list: [CodingList]
    question_instruction_list: [ToneInstructions]
    file_header: DefaultFileHeader
    answer_prompt: DefaultAnswerPrompt
    answer_instruction_list: [Default]
    files:
      - train_model_torchtune.ps1
      - merge_lora.py
      - convert_jsonl_to_json.py
  TrainUnsloth:
    iterations: 10
    question_prompt: WithFileName
    generate_question_list: [CodingList]
    question_instruction_list: [ToneInstructions]
    file_header: DefaultFileHeader
    answer_prompt: DefaultAnswerPrompt
    answer_instruction_list: [Default]
    files:
      - train_model_unsloth.ps1
      - train.py
  InstallModel:
    iterations: 10
    question_prompt: WithFileName
    generate_question_list: [CodingList]
    question_instruction_list: [ToneInstructions]
    file_header: DefaultFileHeader
    answer_prompt: DefaultAnswerPrompt
    answer_instruction_list: [Default]
    files:
      - install_model.ps1
  ListModels:
    iterations: 10
    question_prompt: WithFileName
    generate_question_list: [CodingList]
    question_instruction_list: [ToneInstructions]
    file_header: DefaultFileHeader
    answer_prompt: DefaultAnswerPrompt
    answer_instruction_list: [Default]
    files:
      - list_models.ps1
  FineTuningGuide:
    iterations: 10
    question_prompt: NoFileName
    generate_question_list: [DocumentList]
    question_instruction_list: [ToneInstructions]
    file_header: DefaultFileHeader
    answer_prompt: DefaultAnswerPrompt
    answer_instruction_list: [Default]
    files:
      - FineTuningGuide.md
  GenerateTrainingDataGuide:
    iterations: 30
    question_prompt: NoFileName
    generate_question_list: [DocumentList]
    question_instruction_list: [ToneInstructions]
    file_header: DefaultFileHeader
    answer_prompt: DefaultAnswerPrompt
    answer_instruction_list: [Default]
    files:
      - GenerateTrainingDataGuide.md
