global:
  base_dir: qa_generation_input
  output_dir: qa_generation_output
  output_base_path: /var/kolo_data
  ollama_url: http://localhost:11434/api/generate

providers:
  question:
    provider: openai # Use "ollama" or "openai"
    model: gpt-4o-mini
  answer:
    provider: openai # Use "ollama" or "openai"
    model: gpt-4o-mini

QuestionInstructionList:
  - name: 'CasualandFormal'
    instruction:
      - 'For each question write like a casual person that makes grammatical mistakes and typos'
      - 'For each question write like a formal person who is concise and uses correct terminology.'

AnswerInstructionList:
  - name: 'SimpleAndComplex'
    instruction:
      - 'Keep the answer simple and direct.'
      - 'For your answer give a lot of detail.'

GenerateQuestionLists:
  - name: 'DocumentList'
    questions:
      - 'Generate a list of questions where the user wants to know how to do something.'
      - 'Generate a list of questions where the user wants to know a specific thing.'
      - 'Generate a list of questions where the user asks how to do something given their particular situation.'
      - 'Generate a list of questions where the user asks about something broad.'
  - name: 'CodingList'
    questions:
      - 'Generate a list of questions where the user wants to how to use the following code for their particular situation.'
      - 'Generate a list of questions where the user wants to know what a specific thing does in the code.'

FileHeaders:
  - name: 'DefaultFileHeader'
    description: 'The file contents for: {file_name}'

AnswerPrompt:
  - name: 'DefaultAnswerPrompt'
    description: |
      {file_content}
      {instruction}
      {question}

QuestionPrompt:
  - name: 'NoFileName'
    description: |
      {file_content}
      {generate_question}
      {instruction}
      Use the following output format:
        1. <question 1>
        2. <question 2>
        3. <question 3>
      etc.
  - name: 'WithFileName'
    description: |
      {file_content}
      {generate_question}
      {instruction}
      Use the following output format and for each question reference {file_name_list}:
        1. <question 1>
        2. <question 2>
        3. <question 3>
      etc.

file_groups:
  README:
    iterations: 3
    files:
      - README.md
    question_prompt: NoFileName
    generate_question_list: [DocumentList]
    question_instruction_list: [CasualandFormal]
    file_header: DefaultFileHeader
    answer_prompt: DefaultAnswerPrompt
    answer_instruction_list: [SimpleAndComplex]
  UninstallModel:
    iterations: 3
    files:
      - uninstall_model.ps1
    question_prompt: WithFileName
    generate_question_list: [CodingList]
    question_instruction_list: [CasualandFormal]
    file_header: DefaultFileHeader
    answer_prompt: DefaultAnswerPrompt
    answer_instruction_list: [SimpleAndComplex]
