global:
  base_dir: qa_generation_input
  output_dir: qa_generation_output
  output_base_path: /var/kolo_data
  ollama_url: http://localhost:11434/api/generate

providers:
  question:
    provider: openai # Use "ollama" or "openai"
    model: gpt-4o-mini
  answer:
    provider: openai # Use "ollama" or "openai"
    model: gpt-4o-mini

personas:
  question_personas:
    - 'Someone that speaks casually with grammatical mistakes and typos'
    - 'A formal person who is concise and uses correct terminology.'
    - 'Someone new who is asking basic questions.'
    - 'Someone who is in a rush and misses key details.'
    - 'A detail-oriented user who fixates on minor details and seeks precise clarification.'

file_groups:
  README:
    iterations: 25
    files:
      - README.md
    prompts:
      # For question generation:
      question_prompt_headers:
        - 'Generate a list of questions where the user is confused about something.'
        - 'Generate a list of questions where the user wants to know how to do something specific.'
        - 'Generate a list of questions where the user wants to list all the commands they need to run for their situation.'
        - 'Generate a list of questions where the user asks something vague.'
        - 'Generate a list of questions where the user wants to know the difference between things.'
      question_prompt_footer: |
        Please generate a question list:
        1. <question 1>
        2. <question 2>
        3. <question 3>
        etc.
      question_file_prompt_header: 'The file contents for: {file_name}'
      question_context_prompt: '{files_content}'

      # For answer generation:
      answer_file_prompt_header: 'The file contents for: {file_name}'
      answer_context_prompt: '{files_content}'
      answer_question_prompt: 'Based on the file content provided, answer the following question in detail: {question}'
  # UninstallModel:
  #   iterations: 10
  #   files:
  #     - uninstall_model.ps1
  # DeleteModel:
  #   iterations: 10
  #   files:
  #     - delete_model.ps1
  # TrainTorchTune:
  #   iterations: 30
  #   files:
  #     - train_model_torchtune.ps1
  #     - merge_lora.py
  #     - convert_jsonl_to_json.py
  # BuildImage:
  #   iterations: 30
  #   files:
  #     - build_image.ps1
  #     - dockerfile
  #     - supervisord.conf
  # RunContainer:
  #   iterations: 10
  #   files:
  #     - create_and_run_container.ps1
  #     - run_container.ps1
  # TrainUnsloth:
  #   iterations: 30
  #   files:
  #     - train_model_unsloth.ps1
  #     - train.py
  # TrainingPSCommands:
  #   iterations: 30
  #   files:
  #     - train_model_torchtune.ps1
  #     - train_model_unsloth.ps1
  # InstallModel:
  #   iterations: 10
  #   files:
  #     - install_model.ps1
  # ListModels:
  #   iterations: 10
  #   files:
  #     - list_models.ps1
  # CopyScripts:
  #   iterations: 10
  #   files:
  #     - copy_scripts.ps1
  # CopyConfigs:
  #   iterations: 10
  #   files:
  #     - copy_configs.ps1
  # ConnectSSH:
  #   iterations: 10
  #   files:
  #     - connect.ps1
  # FineTuningGuide:
  #   iterations: 30
  #   files:
  #     - FineTuningGuide.md
  #   question_prompt_footer: |
  #     Please generate the following list:
  #     1. <question 1>
  #     2. <question 2>
  #     3. <question 3>
  #     etc.
  # GenerateQAData:
  #   iterations: 30
  #   files:
  #     - generate_qa_data.ps1
  #     - generate_qa_data.py
  #     - generate_qa_config.yaml
  # ConvertQAData:
  #   iterations: 15
  #   files:
  #     - parse_qa_data.py
  #     - convert_qa_output.ps1
  # GenerateTrainingDataGuide:
  #   iterations: 30
  #   files:
  #     - GenerateTrainingDataGuide.md
  # CopyQAInputGeneration:
  #   iterations: 10
  #   files:
  #     - copy_qa_input_generation.ps1
  # GenerateQADataPy:
  #   iterations: 30
  #   files:
  #     - generate_qa_data.py
  # GenerateQADataPs1:
  #   iterations: 10
  #   files:
  #     - generate_qa_data.ps1
  # GenerateQADataYaml:
  #   iterations: 10
  #   files:
  #     - generate_qa_config.yaml
  # DeleteQAGeneration:
  #   iterations: 10
  #   files:
  #     - delete_qa_generation_output.ps1
  # CreateAndrunContainerAMD:
  #   iterations: 10
  #   files:
  #     - create_and_run_container_amd.ps1
  # BuildImageAMD:
  #   iterations: 10
  #   files:
  #     - build_image_amd.ps1
  # TrainModelTorchtuneAMDBoth:
  #   iterations: 10
  #   files:
  #     - train_model_torchtune_amd.ps1
  #     - train_model_torchtune.ps1
  # TrainModelTorchtuneAMD:
  #   iterations: 5
  #   files:
  #     - train_model_torchtune_amd.ps1
  # DockerFileAMD:
  #   iterations: 10
  #   files:
  #     - dockerfile-amd
  #     - dockerfile
  # CopyTrainingData:
  #   iterations: 10
  #   files:
  #     - copy_training_data.ps1
